version: 2
updates:
  # Check for updates to npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "fieldjoshua"

  # Check for updates to Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  # Maintain dependencies for npm (JavaScript/TypeScript)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "javascript"
    versioning-strategy: auto
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*jest*"
          - "*testing-library*"
        exclude-patterns:
          - "@types/*"
      minor-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    security-updates-only: true

  # Maintain dependencies for pip (Python)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"
    versioning-strategy: auto
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "flake8*"
          - "black"
      ai-dependencies:
        patterns:
          - "openai"
          - "anthropic"
          - "google-generativeai"
          - "cohere"
      web-dependencies:
        patterns:
          - "fastapi"
          - "uvicorn"
          - "starlette"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    security-updates-only: true

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
