# Gitleaks configuration for UltrAI-Core

title = "UltrAI-Core Secret Scanning"

# Add custom rules for our specific patterns
[[rules]]
id = "jwt-secret-hardcoded"
description = "Hardcoded JWT secret"
regex = '''JWT_SECRET\s*=\s*["'][0-9a-zA-Z\-_]{20,}["']'''
tags = ["secret", "jwt"]

[[rules]]
id = "api-key-hardcoded"
description = "Hardcoded API key"
regex = '''API_KEY\s*=\s*["'][0-9a-zA-Z\-_]{20,}["']'''
tags = ["secret", "api-key"]

[[rules]]
id = "ultrai-api-key"
description = "UltrAI API key pattern"
regex = '''ultra_[0-9a-zA-Z\-_]{32,}'''
tags = ["secret", "api-key", "ultrai"]

# Allowlist configuration
[allowlist]
description = "Allowlisted files and patterns"

# Regex patterns to allow
regexes = [
  '''1W3-55MhQfFnkkC4REHcDXPWwTAP7AEqYuJAw-DZEJxHEtrn_97ayLZOn2Q7gSKNZnipY4-0D6niB30v7ztBWA''',
  '''KTIBDNlXkcg7PtZsV6pfqzpm6Nyz8REDQrnKTHJyG3egwXO87ibZDOfs6aO2vksB5LBIUVzFW2A-qOIJ9HAYBg''',
  '''your-.*-here''',
  '''test.*secret|secret.*test|mock.*secret|dummy.*secret''',
  '''sk-ant-test-mock-key-for-testing'''
]

# File paths to allow
paths = [
  '''.env.example''',
  '''test_.*''',
  '''.*_test\..*''',
  '''node_modules''',
  '''venv''',
  '''.venv'''
]

# Extend the default rules
[extend]
useDefault = true
