repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bandit
          - flake8-bugbear
        args:
          - --max-line-length=88
          - --per-file-ignores=src/data/cache/unified_cache.py:B301,B403
        exclude: ^(node_modules/|dist/|build/|.venv/|.env/)

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --line-length=88

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.25.1
    hooks:
      - id: eslint
        files: \.(js|ts|jsx|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@9.0.0-beta.2
          - eslint-plugin-react@7.33.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-config-prettier

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.25.1
    hooks:
      - id: gitleaks

  # Add a dedicated Bandit hook that uses our configuration
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", ".bandit.yaml"]
        exclude: ^(node_modules/|dist/|build/|.venv/|.env/|tests/)
