[build]
  publish = "."
  command = "echo 'Static HTML deployment - no build needed'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  PYTHON_VERSION = ""
  NODE_VERSION = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200