[build]
base = "UltrAI-Core/frontend"
publish = "UltrAI-Core/frontend/dist"
command = "npm ci && npm run build"

[build.environment]
NODE_VERSION = "20"
VITE_API_URL = "https://ultrai-core.onrender.com"
