services:
  # Backend API (Ultra Minimal - Health Check Only)
  - type: web
    name: ultra-backend
    runtime: python
    buildCommand: "pip install -r requirements-ultra-minimal.txt"
    startCommand: "gunicorn app_health_only:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
