services:
  - type: web
    name: ultrai-core
    env: python
    plan: free
    rootDir: ./app
    buildCommand: pip install -r ../requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ENABLE_AUTH
        value: true
      - key: ENABLE_RATE_LIMIT
        value: true
      - key: ENABLE_CACHE
        value: true
      - key: MOCK_MODE
        value: false
      - key: DEFAULT_PROVIDER
        value: openai
      - key: DEFAULT_MODEL
        value: gpt-4-turbo
      - key: DATABASE_URL
        fromDatabase:
          name: ultrai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ultrai-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: CSP_POLICY
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; object-src 'none'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://unpkg.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://unpkg.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; frame-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; worker-src 'self' blob:; connect-src 'self' https://ultrai-core.onrender.com https://ultrai-core-4lut.onrender.com wss://ultrai-core.onrender.com wss://ultrai-core-4lut.onrender.com https://api.ultrai.app wss://api.ultrai.app http://localhost:* ws://localhost:*;"

databases:
  - name: ultrai-db
    databaseName: ultrai_production
    user: ultrai_user
    plan: free

services:
  - type: redis
    name: ultrai-redis
    plan: free
    maxmemoryPolicy: allkeys-lru