services:
  - type: web
    name: ultrai-core
    runtime: python
    buildCommand: "pip install -r requirements-production.txt"
    startCommand: "uvicorn app_production:app --host 0.0.0.0 --port $PORT"
    envVars:
      # Core Settings
      - key: ENVIRONMENT
        value: production
      - key: PORT
        fromService:
          type: web
          name: ultrai-core
          envVarKey: PORT
          
      # P1 Features - Authentication
      - key: ENABLE_AUTH
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
        
      # P1 Features - Rate Limiting
      - key: ENABLE_RATE_LIMIT
        value: "true"
        
      # P1 Features - Telemetry
      - key: OTEL_ENABLED
        value: "true"
      - key: OTEL_SERVICE_NAME
        value: ultrai-core
        
      # Security
      - key: CORS_ALLOWED_ORIGINS
        value: https://ultrai-core.onrender.com
        
      # Python
      - key: PYTHON_VERSION
        value: "3.11"