services:
  # Backend API with integrated frontend (no frontend build needed)
  - type: web
    name: ultrai-core
    runtime: python
    buildCommand: "pip install fastapi uvicorn python-multipart sqlalchemy psycopg2-binary pyjwt passlib[bcrypt] redis python-dotenv pydantic"
    startCommand: "uvicorn app_production:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    # Disable automatic Node.js detection
    ignoredPaths:
      - frontend/
      - frontend/**