services:
  # Backend API (Ultra Minimal - Health Check Only)
  - type: web
    name: ultra-backend
    runtime: python
    buildCommand: "pip install -r requirements-ultra-minimal.txt"
    startCommand: "chmod +x scripts/start-render-minimal.sh && ./scripts/start-render-minimal.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
