services:
  # Backend API with integrated frontend
  - type: web
    name: ultrai-core
    runtime: python
    buildCommand: "pip install -r requirements-production.txt"
    startCommand: "uvicorn app_production:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health