services:
  # Backend API with integrated static frontend (Python only)
  - type: web
    name: ultrai-core
    runtime: python
    buildCommand: "echo 'Installing Python dependencies...' && pip install -r requirements-production.txt"
    startCommand: "uvicorn app_production:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: DISABLE_FRONTEND_BUILD
        value: "true"
    healthCheckPath: /health