#!/bin/bash
# API Key Rotation Checklist
# IMPORTANT: You must do this manually - only you have account access

echo "🚨 CRITICAL: API KEY ROTATION REQUIRED"
echo "====================================="
echo ""
echo "Your API keys were exposed in the git repository and must be rotated immediately."
echo ""
echo "Step 1: OpenAI"
echo "--------------"
echo "1. Go to: https://platform.openai.com/api-keys"
echo "2. Find and revoke any compromised keys"
echo "3. Look for keys that may have been exposed"
echo "4. Click 'Create new secret key'"
echo "5. Copy the new key and save it securely"
echo ""
echo "Step 2: Anthropic"
echo "-----------------"
echo "1. Go to: https://console.anthropic.com/settings/keys"
echo "2. Find and revoke any compromised keys"
echo "3. Look for keys that may have been exposed"
echo "4. Click 'Create Key'"
echo "5. Copy the new key and save it securely"
echo ""
echo "Step 3: Google"
echo "--------------"
echo "1. Go to: https://console.cloud.google.com/apis/credentials"
echo "2. Find and delete any compromised keys"
echo "3. Look for keys that may have been exposed"
echo "4. Click 'CREATE CREDENTIALS' > 'API Key'"
echo "5. Copy the new key and save it securely"
echo ""
echo "Step 4: Update Render"
echo "--------------------"
echo "1. Go to: https://dashboard.render.com/web/srv-cp2i4nmd3nmc73ceaphg/env"
echo "2. Update these environment variables:"
echo "   - OPENAI_API_KEY = [your new OpenAI key]"
echo "   - ANTHROPIC_API_KEY = [your new Anthropic key]"
echo "   - GOOGLE_API_KEY = [your new Google key]"
echo "3. Also add these NEW security variables:"
echo "   - JWT_SECRET_KEY = $(openssl rand -hex 32)"
echo "   - JWT_REFRESH_SECRET_KEY = $(openssl rand -hex 32)"
echo ""
echo "Step 5: Update Local .env"
echo "-------------------------"
echo "1. Copy .env.secure to .env:"
echo "   cp .env.secure .env"
echo "2. Add your NEW API keys to .env (never commit this file!)"
echo ""
echo "Step 6: Clean Git History"
echo "-------------------------"
echo "# Remove .env from git history completely"
echo "git filter-branch --force --index-filter \\"
echo "  'git rm --cached --ignore-unmatch .env' \\"
echo "  --prune-empty --tag-name-filter cat -- --all"
echo ""
echo "# Force push to update remote"
echo "git push origin --force --all"
echo "git push origin --force --tags"
echo ""
echo "⏰ DO THIS NOW - Every minute counts!"
echo "Attackers could be using your keys right now!"