services:
  # UltraAI Feather Orchestrator with proper backend
  - type: web
    name: ultrai-core
    runtime: python
    buildCommand: "echo 'Installing Python dependencies...' && pip install -r requirements-production.txt"
    startCommand: "uvicorn app_production:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: USE_MOCK
        value: "false"
      - key: MOCK_MODE
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY_ENCRYPTION_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://ultrai-core-4lut.onrender.com,https://ultrai-core.onrender.com,https://ultrai-frontend.onrender.com"
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DISABLE_FRONTEND_BUILD
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    healthCheckPath: /health