version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8085
    depends_on:
      - backend
    networks:
      - ultra-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./:/app
      - /app/.venv
    ports:
      - "8085:8085"
    environment:
      - PYTHONPATH=/app
      - PORT=8085
      - DEVELOPMENT=true
    networks:
      - ultra-network

networks:
  ultra-network:
    driver: bridge 