llama:
  api_key: "your-llama-key"
  max_tokens: 1000
  temperature: 0.7
  timeout: 30
  base_url: "http://your-llama-endpoint"

chatgpt:
  api_key: "your-openai-key"
  max_tokens: 1000
  temperature: 0.7
  timeout: 30

gemini:
  api_key: "your-gemini-key"
  max_tokens: 1000
  temperature: 0.7
  timeout: 30
  base_url: "https://generativelanguage.googleapis.com"

orchestrator:
  cache_enabled: true
  max_retries: 3
  max_cache_age_hours: 24
  log_level: "INFO"
  quality_evaluation_enabled: true
