global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ultrai-core'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - "alert-rules.yml"

scrape_configs:
  # Scrape UltraAI Core application
  - job_name: 'ultrai-core'
    static_configs:
      - targets: ['host.docker.internal:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ultrai-core-prod'
    metrics_path: '/api/metrics'

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # Scrape Redis Exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']

  # Scrape Postgres Exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']