version: '3.8'

services:
  # Test Database
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ultra_test
      POSTGRES_USER: ultra_test
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ultra_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Test Redis
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Mock LLM Service
  mock-llm:
    build:
      context: .
      dockerfile: Dockerfile.mock-llm
    ports:
      - "8086:8086"
    environment:
      - RESPONSE_DELAY=0.5
      - ERROR_RATE=0.05
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Test Application
  test-app:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://ultra_test:test_password@test-db:5432/ultra_test
      - REDIS_URL=redis://test-redis:6379
      - USE_MOCK=true
      - MOCK_LLM_URL=http://mock-llm:8086
      - ENVIRONMENT=testing
    ports:
      - "8087:8085"
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      mock-llm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cypress E2E Tests
  cypress:
    image: cypress/included:12.17.1
    depends_on:
      test-app:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://test-app:8085
    volumes:
      - ../e2e:/e2e
      - ../e2e/videos:/e2e/videos
      - ../e2e/screenshots:/e2e/screenshots
    working_dir: /e2e
    command: cypress run

  # Locust Performance Tests
  locust:
    image: locustio/locust
    depends_on:
      test-app:
        condition: service_healthy
    ports:
      - "8089:8089"
    volumes:
      - ../performance:/performance
    working_dir: /performance
    command: -f locustfile.py --host=http://test-app:8085

networks:
  default:
    name: ultra-test-network
