name: NPM Security Scan

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Run snyk test (if available)
        continue-on-error: true  # Don't fail the workflow if snyk isn't set up
        run: |
          if command -v snyk &> /dev/null; then
            snyk test --severity-threshold=high
          else
            echo "Snyk not installed, skipping"
          fi