name: Python Security Scan

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install safety bandit

      - name: Run safety check
        run: safety check

      - name: Run bandit for code security scan
        run: bandit -r . -x ".venv,./node_modules" -ll

      - name: Check for vulnerable Python packages
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY || '' }}
          ignore-cvs: ''  # Add specific CVEs to ignore if needed
          ignore-vulnerabilities: ''
          continue-on-error: true