name: Ultra Tests

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]
  workflow_dispatch:

jobs:
  offline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run offline tests
        run: |
          TEST_MODE=offline pytest -v -m "not live and not live_online and not e2e" \
            --html=report_offline.html --self-contained-html --alluredir=allure-results || true
      - uses: actions/upload-artifact@v4
        with:
          name: offline-report
          path: |
            report_offline.html
            allure-results

  live:
    needs: offline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run live provider smoke
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
        run: |
          TEST_MODE=live pytest -v -m live \
            --html=report_live.html --self-contained-html --alluredir=allure-results || true
      - uses: actions/upload-artifact@v4
        with:
          name: live-report
          path: |
            report_live.html
            allure-results

  demo:
    needs: live
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run demo (staging) endpoint tests
        env:
          DEMO_BASE_URL: ${{ secrets.DEMO_BASE_URL }}
        run: |
          TEST_MODE=live pytest -v -k "test_demo_" -m live \
            --html=report_demo.html --self-contained-html --alluredir=allure-results || true
      - uses: actions/upload-artifact@v4
        with:
          name: demo-report
          path: |
            report_demo.html
            allure-results

